/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercicesIndexRouteImport } from './routes/exercices/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ExercicesTodosRouteImport } from './routes/exercices/todos'
import { Route as ExercicesSearchRouteImport } from './routes/exercices/search'
import { Route as ExercicesCounterRouteImport } from './routes/exercices/counter'
import { Route as ExercicesRootRouteImport } from './routes/exercices/_root'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesIndexRoute = ExercicesIndexRouteImport.update({
  id: '/exercices/',
  path: '/exercices/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const ExercicesTodosRoute = ExercicesTodosRouteImport.update({
  id: '/exercices/todos',
  path: '/exercices/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesSearchRoute = ExercicesSearchRouteImport.update({
  id: '/exercices/search',
  path: '/exercices/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesCounterRoute = ExercicesCounterRouteImport.update({
  id: '/exercices/counter',
  path: '/exercices/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesRootRoute = ExercicesRootRouteImport.update({
  id: '/exercices/_root',
  path: '/exercices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/users': typeof UsersRouteWithChildren
  '/exercices': typeof ExercicesRootRoute
  '/exercices/counter': typeof ExercicesCounterRoute
  '/exercices/search': typeof ExercicesSearchRoute
  '/exercices/todos': typeof ExercicesTodosRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/exercices/': typeof ExercicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/users': typeof UsersRouteWithChildren
  '/exercices': typeof ExercicesIndexRoute
  '/exercices/counter': typeof ExercicesCounterRoute
  '/exercices/search': typeof ExercicesSearchRoute
  '/exercices/todos': typeof ExercicesTodosRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/users': typeof UsersRouteWithChildren
  '/exercices/_root': typeof ExercicesRootRoute
  '/exercices/counter': typeof ExercicesCounterRoute
  '/exercices/search': typeof ExercicesSearchRoute
  '/exercices/todos': typeof ExercicesTodosRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/exercices/': typeof ExercicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/users'
    | '/exercices'
    | '/exercices/counter'
    | '/exercices/search'
    | '/exercices/todos'
    | '/users/$userId'
    | '/exercices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/users'
    | '/exercices'
    | '/exercices/counter'
    | '/exercices/search'
    | '/exercices/todos'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/users'
    | '/exercices/_root'
    | '/exercices/counter'
    | '/exercices/search'
    | '/exercices/todos'
    | '/users/$userId'
    | '/exercices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UsersRoute: typeof UsersRouteWithChildren
  ExercicesRootRoute: typeof ExercicesRootRoute
  ExercicesCounterRoute: typeof ExercicesCounterRoute
  ExercicesSearchRoute: typeof ExercicesSearchRoute
  ExercicesTodosRoute: typeof ExercicesTodosRoute
  ExercicesIndexRoute: typeof ExercicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/': {
      id: '/exercices/'
      path: '/exercices'
      fullPath: '/exercices/'
      preLoaderRoute: typeof ExercicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/exercices/todos': {
      id: '/exercices/todos'
      path: '/exercices/todos'
      fullPath: '/exercices/todos'
      preLoaderRoute: typeof ExercicesTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/search': {
      id: '/exercices/search'
      path: '/exercices/search'
      fullPath: '/exercices/search'
      preLoaderRoute: typeof ExercicesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/counter': {
      id: '/exercices/counter'
      path: '/exercices/counter'
      fullPath: '/exercices/counter'
      preLoaderRoute: typeof ExercicesCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices/_root': {
      id: '/exercices/_root'
      path: '/exercices'
      fullPath: '/exercices'
      preLoaderRoute: typeof ExercicesRootRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UsersRoute: UsersRouteWithChildren,
  ExercicesRootRoute: ExercicesRootRoute,
  ExercicesCounterRoute: ExercicesCounterRoute,
  ExercicesSearchRoute: ExercicesSearchRoute,
  ExercicesTodosRoute: ExercicesTodosRoute,
  ExercicesIndexRoute: ExercicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
